In [1]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv("Online Retail Data Set.csv")

In [4]:
df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/10 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/10 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/10 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/10 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/10 8:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/11 12:50,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/11 12:50,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/11 12:50,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/11 12:50,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/11 12:50,4.95,12680.0,France

In [5]:
df = df[(df['Quantity'] >= 1) & (df['UnitPrice'] > 0)]

In [6]:
df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/10 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/10 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/10 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/10 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/10 8:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/11 12:50,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/11 12:50,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/11 12:50,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/11 12:50,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/11 12:50,4.95,12680.0,France

In [7]:
df = df.dropna(subset=['CustomerID'])

In [8]:
df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/10 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/10 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/10 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/10 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/10 8:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/11 12:50,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/11 12:50,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/11 12:50,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/11 12:50,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/11 12:50,4.95,12680.0,France

In [9]:
df['Revenue'] = df['Quantity'] * df['UnitPrice']

C:\Users\vajra\AppData\Local\Temp\ipykernel_7296\1867220470.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Revenue'] = df['Quantity'] * df['UnitPrice']

In [10]:
df['Revenue']

0         15.30
1         20.34
2         22.00
3         20.34
4         20.34
          ...
541904    10.20
541905    12.60
541906    16.60
541907    16.60
541908    14.85
Name: Revenue, Length: 397884, dtype: float64

In [13]:
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])
df['Year'] = df['InvoiceDate'].dt.year
df['Month'] = df['InvoiceDate'].dt.month
df['MonthName'] = df['InvoiceDate'].dt.strftime('%b')

C:\Users\vajra\AppData\Local\Temp\ipykernel_7296\3693663881.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])
C:\Users\vajra\AppData\Local\Temp\ipykernel_7296\3693663881.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Year'] = df['InvoiceDate'].dt.year
C:\Users\vajra\AppData\Local\Temp\ipykernel_7296\3693663881.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Month'] = df['InvoiceDate'].dt.month
C:\Users\vajra\AppData\Local\Temp\ipykernel_7296\3693663881.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['MonthName'] = df['InvoiceDate'].dt.strftime('%b')

In [12]:
df['InvoiceDate']

0        2010-12-01 08:26:00
1        2010-12-01 08:26:00
2        2010-12-01 08:26:00
3        2010-12-01 08:26:00
4        2010-12-01 08:26:00
                 ...
541904   2011-12-09 12:50:00
541905   2011-12-09 12:50:00
541906   2011-12-09 12:50:00
541907   2011-12-09 12:50:00
541908   2011-12-09 12:50:00
Name: InvoiceDate, Length: 397884, dtype: datetime64[ns]

In [14]:
df['Year']

0         2010
1         2010
2         2010
3         2010
4         2010
          ...
541904    2011
541905    2011
541906    2011
541907    2011
541908    2011
Name: Year, Length: 397884, dtype: int32

In [15]:
df['Month']

0         12
1         12
2         12
3         12
4         12
          ..
541904    12
541905    12
541906    12
541907    12
541908    12
Name: Month, Length: 397884, dtype: int32

In [19]:
df['MonthName']

0         Dec
1         Dec
2         Dec
3         Dec
4         Dec
         ...
541904    Dec
541905    Dec
541906    Dec
541907    Dec
541908    Dec
Name: MonthName, Length: 397884, dtype: object

In [32]:
q1 = df[df['Year'] == 2011].groupby(['Month','MonthName'])['Revenue'].sum().reset_index().sort_values('Month')
q1

    Month MonthName      Revenue
0       1       Jan   569445.040
1       2       Feb   447137.350
2       3       Mar   595500.760
3       4       Apr   469200.361
4       5       May   678594.560
5       6       Jun   661213.690
6       7       Jul   600091.011
7       8       Aug   645343.900
8       9       Sep   952838.382
9      10       Oct  1039318.790
10     11       Nov  1161817.380
11     12       Dec   518192.790

In [22]:
q2 = df[df['Country'] != 'United Kingdom'].groupby('Country').agg({'Revenue':'sum','Quantity':'sum'}).reset_index()
q2 = q2.sort_values('Revenue', ascending=False).head(10)

In [23]:
q2

        Country    Revenue  Quantity
23  Netherlands  285446.34    200361
10         EIRE  265545.90    140275
14      Germany  228867.14    119261
13       France  209024.05    111471
0     Australia  138521.31     83901
30        Spain   61577.11     27940
32  Switzerland   56443.95     30082
3       Belgium   41196.34     23237
31       Sweden   38378.33     36083
19        Japan   37416.37     26016

In [28]:
q3 = df.groupby('CustomerID')['Revenue'].sum().reset_index().sort_values('Revenue', ascending=False).head(10)
q3

      CustomerID    Revenue
1689     14646.0  280206.02
4201     18102.0  259657.30
3728     17450.0  194550.79
3008     16446.0  168472.50
1879     14911.0  143825.06
55       12415.0  124914.53
1333     14156.0  117379.63
3771     17511.0   91062.38
2702     16029.0   81024.84
0        12346.0   77183.60

In [27]:
q4 = df[df['Country'] != 'United Kingdom'].groupby('Country')['Quantity'].sum().reset_index()
q4

                 Country  Quantity
0              Australia     83901
1                Austria      4881
2                Bahrain       260
3                Belgium     23237
4                 Brazil       356
5                 Canada      2763
6        Channel Islands      9491
7                 Cyprus      6361
8         Czech Republic       671
9                Denmark      8235
10                  EIRE    140275
11    European Community       499
12               Finland     10704
13                France    111471
14               Germany    119261
15                Greece      1557
16               Iceland      2458
17                Israel      4046
18                 Italy      8112
19                 Japan     26016
20               Lebanon       386
21             Lithuania       652
22                 Malta       970
23           Netherlands    200361
24                Norway     19336
25                Poland      3684
26              Portugal     16122
27                   RSA       351
28          Saudi Arabia        80
29             Singapore      5241
30                 Spain     27940
31                Sweden     36083
32           Switzerland     30082
33                   USA      2458
34  United Arab Emirates       982
35           Unspecified      1789

In [33]:
q1.to_excel(Country, sheet_name='Question 1', index=False)
q2.to_excel(Year, sheet_name='Question 2', index=False)
q3.to_excel(CustomerID,sheet_name='Question 3', index=False)
q4.to_excel(Revenue, sheet_name='Question 4', index=False)

NameError: name 'Country' is not defined